export const dailyGoals = [
  {
    id: "1",
    title: "Reduce water usage",
    description: "Take a shorter shower (under 5 minutes) and turn off taps when not in use.",
    why: "Freshwater is only 3% of Earth's water. Reducing usage helps preserve aquifers and reduces energy used for water treatment.",
    impact: "Saves up to 40 liters of water per day",
    trees: 5,
    completed: false,
    category: "water",
  },
  {
    id: "2",
    title: "Avoid single-use plastics",
    description: "Use a reusable bottle, bag, and container for all meals today.",
    why: "Over 8 million tons of plastic enter oceans yearly. Single-use plastics take 400+ years to decompose and harm marine ecosystems.",
    impact: "Prevents ~1.5 kg of plastic waste per week",
    trees: 5,
    completed: false,
    category: "waste",
  },
  {
    id: "3",
    title: "Use public transport or walk",
    description: "Skip driving alone. Walk, cycle, or take public transport for your commute.",
    why: "Transport accounts for ~24% of global CO2 emissions. Walking/cycling produces zero emissions.",
    impact: "Saves 2.6 kg of CO2 per 10 km avoided by car",
    trees: 8,
    completed: false,
    category: "transport",
  },
  {
    id: "4",
    title: "Reduce electricity consumption",
    description: "Turn off lights, unplug chargers, and use natural lighting when possible.",
    why: "Electricity generation is the largest source of greenhouse gas emissions globally. Every watt saved reduces fossil fuel burning.",
    impact: "Saves up to 1 kg of CO2 per day",
    trees: 5,
    completed: false,
    category: "energy",
  },
  {
    id: "5",
    title: "Eat a plant-based meal",
    description: "Replace at least one meal with a fully plant-based option today.",
    why: "Animal agriculture produces 14.5% of global greenhouse gases. Plant-based meals use 75% less land and 54% less water.",
    impact: "Saves 2.5 kg of CO2 per meal replaced",
    trees: 6,
    completed: false,
    category: "food",
  },
  {
    id: "6",
    title: "Compost food scraps",
    description: "Separate your fruit/vegetable peels and food waste for composting.",
    why: "Food waste in landfills produces methane, a greenhouse gas 80x more potent than CO2. Composting returns nutrients to soil.",
    impact: "Diverts 0.5 kg of waste from landfill per day",
    trees: 4,
    completed: false,
    category: "waste",
  },
]

export const communityPosts = [
  {
    id: "movement-cleanliness-1",
    username: "ReGen Community",
    avatar: "RC",
    content: "Join our Cleanliness Drive this Saturday at Baradari Garden! We'll be removing plastic waste and planting saplings. Bring gloves and water. Together we can make Patiala greener.",
    upvotes: 312,
    comments: 48,
    category: "waste",
    city: "Patiala",
    timeAgo: "1d ago",
    movement: { id: "cleanliness-drive-1", name: "Cleanliness Drive" },
  },
  {
    id: "1",
    username: "ArjunS",
    avatar: "AS",
    content: "The Bhakra Canal has been polluted heavily near sector 12. We need to raise this with local authorities. Anyone willing to organize a cleanup drive this weekend?",
    upvotes: 47,
    comments: 12,
    category: "water",
    city: "Patiala",
    timeAgo: "2h ago",
  },
  {
    id: "2",
    username: "PriyaK",
    avatar: "PK",
    content: "Planted 15 saplings near Rajindra Hospital with the ReGen community! Small steps, big impact. Join us every Sunday morning.",
    upvotes: 89,
    comments: 23,
    category: "deforestation",
    city: "Patiala",
    timeAgo: "4h ago",
  },
  {
    id: "3",
    username: "MandeepR",
    avatar: "MR",
    content: "Stubble burning smoke is getting worse this season. AQI was 340 yesterday. Has anyone tried speaking to the local farming cooperative?",
    upvotes: 156,
    comments: 45,
    category: "air",
    city: "Patiala",
    timeAgo: "6h ago",
  },
  {
    id: "4",
    username: "SimranG",
    avatar: "SG",
    content: "Started a composting pit in our colony. If anyone in Model Town wants to join in, DM me! We can reduce so much kitchen waste together.",
    upvotes: 34,
    comments: 8,
    category: "waste",
    city: "Patiala",
    timeAgo: "8h ago",
  },
  {
    id: "5",
    username: "RaviT",
    avatar: "RT",
    content: "The local nala near Leela Bhawan is overflowing with plastic waste. This is a breeding ground for diseases. We need municipal action ASAP.",
    upvotes: 203,
    comments: 67,
    category: "waste",
    city: "Patiala",
    timeAgo: "10h ago",
  },
  {
    id: "6",
    username: "NavjotP",
    avatar: "NP",
    content: "Organized a cycle-to-work campaign in our office. 15 people participated today! Saved approx 40 kg CO2. Every ride counts.",
    upvotes: 62,
    comments: 15,
    category: "transport",
    city: "Patiala",
    timeAgo: "12h ago",
  },
  {
    id: "7",
    username: "AnikaD",
    avatar: "AD",
    content: "Why aren't there more recycling bins in Patiala? I had to walk 2 km to find one. We should petition for better waste infrastructure.",
    upvotes: 128,
    comments: 34,
    category: "waste",
    city: "Patiala",
    timeAgo: "1d ago",
  },
  {
    id: "8",
    username: "HarjotB",
    avatar: "HB",
    content: "Great news! The solar panel installation at Punjabi University campus is now operational. Clean energy for 500+ students!",
    upvotes: 215,
    comments: 52,
    category: "energy",
    city: "Patiala",
    timeAgo: "1d ago",
  },
  {
    id: "9",
    username: "DeepakL",
    avatar: "DL",
    content: "Found a new plant-based restaurant near Bus Stand. Delicious food with zero carbon guilt. Supporting local sustainable businesses matters!",
    upvotes: 45,
    comments: 11,
    category: "food",
    city: "Patiala",
    timeAgo: "1d ago",
  },
  {
    id: "10",
    username: "KamalJ",
    avatar: "KJ",
    content: "The groundwater table in Patiala has dropped 3 meters in the last decade. We need to push for rainwater harvesting in every household. Who is with me?",
    upvotes: 178,
    comments: 41,
    category: "water",
    city: "Patiala",
    timeAgo: "2d ago",
  },
]

export const cityPosts: Record<string, typeof communityPosts> = {
  Mumbai: [
    {
      id: "m1",
      username: "RahulV",
      avatar: "RV",
      content: "Versova Beach cleanup drive this Saturday! Last month we collected 2 tons of plastic. Let's beat that record!",
      upvotes: 342,
      comments: 89,
      category: "waste",
      city: "Mumbai",
      timeAgo: "3h ago",
    },
    {
      id: "m2",
      username: "MeeraS",
      avatar: "MS",
      content: "Mangrove destruction near Airoli is alarming. These are our natural flood barriers. We need stricter protection laws.",
      upvotes: 567,
      comments: 123,
      category: "deforestation",
      city: "Mumbai",
      timeAgo: "5h ago",
    },
    {
      id: "m3",
      username: "AkashP",
      avatar: "AP",
      content: "Air quality near BKC has improved 15% since the new metro line opened. Public transport works!",
      upvotes: 234,
      comments: 56,
      category: "air",
      city: "Mumbai",
      timeAgo: "1d ago",
    },
  ],
  Delhi: [
    {
      id: "d1",
      username: "AyushM",
      avatar: "AM",
      content: "Yamuna cleanup initiative needs volunteers! Meeting point: ITO Bridge, Sunday 7AM. Bring gloves!",
      upvotes: 456,
      comments: 98,
      category: "water",
      city: "Delhi",
      timeAgo: "2h ago",
    },
    {
      id: "d2",
      username: "NehaN",
      avatar: "NN",
      content: "AQI hit 450 today near Anand Vihar. Schools should switch to online mode. Our children's health cannot wait.",
      upvotes: 891,
      comments: 234,
      category: "air",
      city: "Delhi",
      timeAgo: "4h ago",
    },
    {
      id: "d3",
      username: "VikasR",
      avatar: "VR",
      content: "Biodiversity Park in South Delhi is thriving! 47 bird species spotted last month. Proof that urban restoration works.",
      upvotes: 312,
      comments: 67,
      category: "deforestation",
      city: "Delhi",
      timeAgo: "8h ago",
    },
  ],
  London: [
    {
      id: "l1",
      username: "EmmaN",
      avatar: "EN",
      content: "The Thames is the cleanest it's been in 60 years! Community-led monitoring programs are making a difference.",
      upvotes: 678,
      comments: 145,
      category: "water",
      city: "London",
      timeAgo: "1h ago",
    },
    {
      id: "l2",
      username: "JamesW",
      avatar: "JW",
      content: "Ultra Low Emission Zone expansion has cut NO2 by 20%. Real policy, real results. Other cities should take note.",
      upvotes: 534,
      comments: 112,
      category: "air",
      city: "London",
      timeAgo: "6h ago",
    },
    {
      id: "l3",
      username: "SophieT",
      avatar: "ST",
      content: "Community garden in Hackney is flourishing! Growing local food, building community, and cutting food miles all at once.",
      upvotes: 289,
      comments: 78,
      category: "food",
      city: "London",
      timeAgo: "1d ago",
    },
  ],
}

export const climateFacts = [
  "The last decade was the warmest in 125,000 years.",
  "Forests absorb about 2.6 billion tonnes of CO2 annually.",
  "Ice sheets in Greenland and Antarctica lose 427 billion tons of ice yearly.",
  "Renewable energy now provides 30% of global electricity.",
  "A single tree absorbs about 22 kg of CO2 per year.",
  "Switching to LEDs saves 75% more energy than incandescent bulbs.",
  "Ocean temperatures have risen by 0.88C since pre-industrial times.",
  "Plant-based diets can reduce food-related emissions by up to 73%.",
]

export const cities = [
  {
    id: "mumbai",
    name: "Mumbai",
    country: "India",
    activeUsers: 12400,
    issues: 234,
    image: "mumbai",
  },
  {
    id: "delhi",
    name: "Delhi",
    country: "India",
    activeUsers: 18900,
    issues: 567,
    image: "delhi",
  },
  {
    id: "london",
    name: "London",
    country: "UK",
    activeUsers: 8700,
    issues: 145,
    image: "london",
  },
  {
    id: "patiala",
    name: "Patiala",
    country: "India",
    activeUsers: 3200,
    issues: 89,
    image: "patiala",
  },
]

export const authorities = [
  {
    city: "Patiala",
    authorities: [
      {
        name: "Punjab Pollution Control Board",
        phone: "+91-175-2211665",
        email: "ppcb@punjab.gov.in",
        purpose: "Air & water pollution complaints",
      },
      {
        name: "Municipal Corporation Patiala",
        phone: "+91-175-2213576",
        email: "mc.patiala@punjab.gov.in",
        purpose: "Waste management & sanitation",
      },
      {
        name: "District Forest Officer, Patiala",
        phone: "+91-175-2214456",
        email: "dfo.patiala@punjab.gov.in",
        purpose: "Deforestation & wildlife concerns",
      },
    ],
  },
  {
    city: "Mumbai",
    authorities: [
      {
        name: "Maharashtra Pollution Control Board",
        phone: "+91-22-24010437",
        email: "mpcb@maharashtra.gov.in",
        purpose: "Air & water pollution complaints",
      },
      {
        name: "BMC Environment Department",
        phone: "+91-22-22620251",
        email: "env.bmc@gov.in",
        purpose: "Waste management & urban environment",
      },
    ],
  },
  {
    city: "Delhi",
    authorities: [
      {
        name: "Delhi Pollution Control Committee",
        phone: "+91-11-27187558",
        email: "dpcc@nic.in",
        purpose: "Air quality & pollution control",
      },
      {
        name: "DDA Horticulture Department",
        phone: "+91-11-23379205",
        email: "hort.dda@gov.in",
        purpose: "Urban greening & tree protection",
      },
    ],
  },
  {
    city: "London",
    authorities: [
      {
        name: "Environment Agency",
        phone: "+44-3708-506506",
        email: "enquiries@environment-agency.gov.uk",
        purpose: "Water pollution & flood risk",
      },
      {
        name: "Greater London Authority - Environment",
        phone: "+44-20-79834000",
        email: "environment@london.gov.uk",
        purpose: "Air quality & green spaces",
      },
    ],
  },
]

export const educationResources = [
  {
    id: "1",
    title: "Climate Change Basics",
    source: "NASA",
    url: "https://climate.nasa.gov/evidence/",
    description: "Understand the evidence behind climate change with NASA's comprehensive guide.",
    category: "basics",
  },
  {
    id: "2",
    title: "IPCC Sixth Assessment Report",
    source: "IPCC",
    url: "https://www.ipcc.ch/assessment-report/ar6/",
    description: "The most comprehensive scientific assessment of climate change impacts and solutions.",
    category: "reports",
  },
  {
    id: "3",
    title: "Individual Actions Matter",
    source: "Project Drawdown",
    url: "https://drawdown.org/",
    description: "Discover the most impactful solutions to reverse global warming at every scale.",
    category: "action",
  },
  {
    id: "4",
    title: "The Carbon Footprint of Everything",
    source: "MIT Climate",
    url: "https://climate.mit.edu/",
    description: "Learn how everyday choices impact your carbon footprint and what you can do about it.",
    category: "basics",
  },
  {
    id: "5",
    title: "Ocean and Climate Change",
    source: "NOAA",
    url: "https://www.noaa.gov/education/resource-collections/climate",
    description: "Explore the relationship between oceans, weather patterns, and long-term climate shifts.",
    category: "reports",
  },
  {
    id: "6",
    title: "Youth Climate Action Guide",
    source: "UNEP",
    url: "https://www.unep.org/explore-topics/climate-action",
    description: "A practical guide for young people to take meaningful climate action in their communities.",
    category: "action",
  },
]
